[package]
name = "riablo"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ggez = "0.7"
glam = "0.20.2"
oorandom = "11.1.3"
getrandom = "0.2.3"